AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/*.pryrc'
    - '**/*.rake'
    - '.env'
    - '.simplecov'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/2015*.rb'
    - 'db/migrate/2016*.rb'
Documentation:
  Enabled: false
Lint/HandleExceptions:
  Exclude:
    - 'bin/*'
Metrics/AbcSize:
  Enabled: false
  Max: 17
  Exclude:
    - 'db/migrate/*'
Metrics/ClassLength:
  Exclude:
    - 'db/migrate/*'
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/*'
Metrics/MethodLength:
  Enabled: false
  Exclude:
    - 'db/migrate/*'
Metrics/PerceivedComplexity:
  Enabled: false
Rails/SkipsModelValidations:
  Exclude:
    - 'test/**/*.rb'
Style/Copyright:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/NegatedIf:
  Enabled: true
  EnforcedStyle: postfix
Style/Send:
  Exclude:
    - 'test/**/*.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
